const personaggiStarWars = [
  {
    nome: "Darth Vader",
    img: "https://i.pinimg.com/1200x/3f/f6/fc/3ff6fcecc8d8b3070a073186cdfef406.jpg",
    affiliazione: "Sith",
    attacco: 90,
    difesa: 75,
    livello: 100,
    abilita: "Strangolamento",
  },
  {
    nome: "Luke Skywalker",
    img: "https://w0.peakpx.com/wallpaper/468/241/HD-wallpaper-luke-skywalker-luke-skywalker-star-wars-thumbnail.jpg",
    affiliazione: "Jedi",
    attacco: 85,
    difesa: 80,
    livello: 95,
    abilita: "Colpo della Forza",
  },
  {
    nome: "Yoda",
    img: "https://upload.wikimedia.org/wikipedia/en/9/9b/Yoda_Empire_Strikes_Back.png",
    affiliazione: "Jedi",
    attacco: 78,
    difesa: 95,
    livello: 150,
    abilita: "Telecinesi",
  },
  {
    nome: "Darth Maul",
    img: "https://www.impericon.com/cdn/shop/files/x_hot913363_b_e7404ecf-13e4-4f4d-808c-9a3b2555cd45.jpg",
    affiliazione: "Sith",
    attacco: 92,
    difesa: 70,
    livello: 90,
    abilita: "Doppia spada laser",
  },
  {
    nome: "Obi-Wan Kenobi",
    img: "https://upload.wikimedia.org/wikipedia/en/3/32/Ben_Kenobi.png",
    affiliazione: "Jedi",
    attacco: 80,
    difesa: 85,
    livello: 100,
    abilita: "Manipolazione della mente",
  },
  {
    nome: "Kylo Ren",
    img: "https://www.starshop.it/media/catalog/product/cache/a018a830359f49ee6061d02f0e704676/p/r/prodotti-01169SWFA0001.jpg",
    affiliazione: "Sith",
    attacco: 88,
    difesa: 72,
    livello: 85,
    abilita: "Controllo della Forza",
  },
  {
    nome: "Rey",
    img: "https://i.etsystatic.com/8788928/r/il/9594f8/3763280010/il_794xN.3763280010_rhq9.jpg",
    affiliazione: "Jedi",
    attacco: 82,
    difesa: 78,
    livello: 90,
    abilita: "Empatia della Forza",
  },
  {
    nome: "Boba Fett",
    img: "https://cdn.1001hobbies.it/1718119-large_default/kotobukiya-ktosw194-star-wars-il-libro-di-boba-fett-statuetta-in-pvc-.jpg",
    affiliazione: "Cacciatore di taglie",
    attacco: 75,
    difesa: 80,
    livello: 70,
    abilita: "Jetpack e armi avanzate",
  },
  {
    nome: "Palpatine",
    img: "https://miro.medium.com/v2/resize:fit:720/format:webp/1*Q9pbgovcoS-4E1cUDLVxwg.png",
    affiliazione: "Sith",
    attacco: 95,
    difesa: 85,
    livello: 120,
    abilita: "Fulmini della Forza",
  },
  {
    nome: "General Grievous",
    img: "https://itakon.it/wp-content/uploads/2014/02/General-Grievous-20-532x800.jpg",
    affiliazione: "Separatisti",
    attacco: 90,
    difesa: 65,
    livello: 80,
    abilita: "Quattro spade laser",
  },
];

export default personaggiStarWars;
