const personaggiStarWars = [
  {
    nome: "Darth Vader",
    img: "https://i.pinimg.com/1200x/3f/f6/fc/3ff6fcecc8d8b3070a073186cdfef406.jpg",
    affiliazione: "Sith",
    attacco: 90,
    difesa: 75,
    livello: 100,
    abilita: "Strangolamento",
  },
  {
    nome: "Luke Skywalker",
    img: "https://i.pinimg.com/originals/70/2e/c1/702ec1c19b5999b3fbd87cb88e462923.jpg",
    affiliazione: "Jedi",
    attacco: 85,
    difesa: 80,
    livello: 95,
    abilita: "Colpo della Forza",
  },
  {
    nome: "Yoda",
    img: "https://upload.wikimedia.org/wikipedia/en/9/9b/Yoda_Empire_Strikes_Back.png",
    affiliazione: "Jedi",
    attacco: 78,
    difesa: 95,
    livello: 150,
    abilita: "Telecinesi",
  },
  {
    nome: "Darth Maul",
    img: "https://static.wikia.nocookie.net/starwars/images/9/97/Darth_Maul_profile.png",
    affiliazione: "Sith",
    attacco: 92,
    difesa: 70,
    livello: 90,
    abilita: "Doppia spada laser",
  },
  {
    nome: "Obi-Wan Kenobi",
    img: "https://upload.wikimedia.org/wikipedia/en/3/32/Ben_Kenobi.png",
    affiliazione: "Jedi",
    attacco: 80,
    difesa: 85,
    livello: 100,
    abilita: "Manipolazione della mente",
  },
  {
    nome: "Kylo Ren",
    img: "https://upload.wikimedia.org/wikipedia/en/5/5b/Kylo_Ren_in_Star_Wars_The_Force_Awakens.png",
    affiliazione: "Sith",
    attacco: 88,
    difesa: 72,
    livello: 85,
    abilita: "Controllo della Forza",
  },
  {
    nome: "Rey",
    img: "https://upload.wikimedia.org/wikipedia/en/3/3b/Rey_Star_Wars.png",
    affiliazione: "Jedi",
    attacco: 82,
    difesa: 78,
    livello: 90,
    abilita: "Empatia della Forza",
  },
  {
    nome: "Boba Fett",
    img: "https://upload.wikimedia.org/wikipedia/en/3/3e/Boba_Fett.png",
    affiliazione: "Cacciatore di taglie",
    attacco: 75,
    difesa: 80,
    livello: 70,
    abilita: "Jetpack e armi avanzate",
  },
  {
    nome: "Palpatine",
    img: "https://upload.wikimedia.org/wikipedia/en/9/93/Emperor_RotJ.png",
    affiliazione: "Sith",
    attacco: 95,
    difesa: 85,
    livello: 120,
    abilita: "Fulmini della Forza",
  },
  {
    nome: "General Grievous",
    img: "https://upload.wikimedia.org/wikipedia/en/e/ea/General_Grievous.png",
    affiliazione: "Separatisti",
    attacco: 90,
    difesa: 65,
    livello: 80,
    abilita: "Quattro spade laser",
  },
];

export default personaggiStarWars;
